{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "objex.fullname" . }}-s3
  labels:
    {{- include "objex.labels" . | nindent 4 }}
  {{- with .Values.ingress.s3.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.s3.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.s3.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "objex.fullname" . }}
                port:
                  name: s3
---
{{- if .Values.ingress.ui.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "objex.fullname" . }}-ui
  labels:
    {{- include "objex.labels" . | nindent 4 }}
  {{- with .Values.ingress.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.ui.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.ui.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "objex.fullname" . }}
                port:
                  name: ui
{{- end }}
{{- end }}
