apiVersion: v1
kind: Service
metadata:
  name: {{ include "objex.fullname" . }}
  labels:
    {{- include "objex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ui
      port: {{ .Values.service.uiPort }}
      targetPort: ui
    - name: s3
      port: {{ .Values.service.s3Port }}
      targetPort: s3
  selector:
    {{- include "objex.selectorLabels" . | nindent 4 }}
