version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      radzen:
        patterns:
          - "Radzen.*"
      ef-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      hangfire:
        patterns:
          - "Hangfire.*"
      serilog:
        patterns:
          - "Serilog.*"
      microsoft:
        patterns:
          - "Microsoft.*"
      xunit:
        patterns:
          - "xunit*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns:
          - "*"
