apiVersion: v1
kind: Secret
metadata:
  name: {{ include "objex.secretName" . }}
  labels:
    {{- include "objex.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.admin.password | quote }}
  {{- if .Values.seed.s3Credential.secretAccessKey }}
  s3-secret-access-key: {{ .Values.seed.s3Credential.secretAccessKey | quote }}
  {{- end }}
