// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjeX.Infrastructure.Data;

#nullable disable

namespace ObjeX.Infrastructure.Migrations
{
    [DbContext(typeof(ObjeXDbContext))]
    partial class ObjeXDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ObjeX.Core.Models.BlobObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("BucketName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bucket_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("e_tag");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<string>("StoragePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_blob_objects");

                    b.HasIndex("BucketName", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_blob_objects_bucket_name_key");

                    b.ToTable("blob_objects", (string)null);
                });

            modelBuilder.Entity("ObjeX.Core.Models.Bucket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("ObjectCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("object_count");

                    b.Property<long>("TotalSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_size");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_buckets");

                    b.HasAlternateKey("Name")
                        .HasName("ak_buckets_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_buckets_name");

                    b.ToTable("buckets", (string)null);
                });

            modelBuilder.Entity("ObjeX.Core.Models.BlobObject", b =>
                {
                    b.HasOne("ObjeX.Core.Models.Bucket", "Bucket")
                        .WithMany("Objects")
                        .HasForeignKey("BucketName")
                        .HasPrincipalKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blob_objects_buckets_bucket_name");

                    b.Navigation("Bucket");
                });

            modelBuilder.Entity("ObjeX.Core.Models.Bucket", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
